/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package ${project_package}

import spock.lang.Specification

class ${project_class_name}Spec extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new ${project_class_name}()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
