/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package org.example

import picocli.CommandLine;
import picocli.CommandLine.ArgGroup;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters



@Command(name = "app", mixinStandardHelpOptions = true, version = "Picocli example")
class App implements Runnable {

    // mutually exclusive arguments and there must be 1
    @ArgGroup(exclusive = true, multiplicity = "1")
    OperatorOptions operatorOptions

    static class OperatorOptions {
        @Option(names = ['-a', '--add'], description = 'Add values.')
        boolean add

        @Option(names = ['-s', '--subtract'], description = 'Subtract values.')
        boolean subtract
    }

    // Single-value @Parameters are always mandatory,
    // because single-value positional parameters have arity = "1" by default.
    @Parameters(index = "0")
    Integer operand1

    @Parameters(index = "1")
    Integer operand2

    @Option(names = ['-v', '--verbose'], description = 'Verbose mode. Helpful for troubleshooting.')
    boolean verbose

    Integer result = 0

    void run() {
        if (verbose) {
            println("Verbose option enabled...")
        }


        println("operand1 = ${operand1}")
        println("operand2 = ${operand2}")

        // add/subtract are exclusive options so only one will be used
        if (operatorOptions.add) {
            result = operand1 + operand2
            println("${operand1} + ${operand2} = ${result}")
        }
        if (operatorOptions.subtract) {
            result = operand1 - operand2
            println("${operand1} - ${operand2} = ${result}")
        }

    }

    static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args)
        System.exit(exitCode)
    }
}
