/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ${project_package};

public class ${project_class_name} {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ${project_class_name}().getGreeting());
    }
}
